### ISSUE TITLE
Add remaining CI improvements

### ISSUE THREAD

**Issue by josephlr** [rust-random/getrandom#194]
After #192, we still have a few things we should add to our CI. These include:
- [x] Running the iOS binaries we build (ideally on both x86_64 and aarch64) #316 
- [x] Build and run `aarch64-apple-darwin` binaries (aka "Apple Silicon") #398 
- [x] Add emscripten tests (#196)
- [x] Add no-std test for a `custom` hook (#197)
- [x] ~~Cache toolchain downloads (see actions-rs/meta#21 and actions-rs/toolchain#54)~~ Not useful with move to https://github.com/dtolnay/rust-toolchain
- [x] Cache crates.io downloads/index (#198)

**Comment by josephlr** [comment]
With #316 the only think we are waiting on is AArch64 macOS runners. This is tracked in https://github.com/github/roadmap/issues/528
