### ISSUE TITLE
No-panic check tracking issue

### ISSUE THREAD

**Issue by newpavlov** [rust-random/getrandom#516]
Backends list:
- [ ] apple-other
- [ ] custom
- [ ] esp_idf
- [ ] fuchsia
- [x] getentropy
- [ ] getrandom
- [ ] hermit
- [x] linux_android
- [x] linux_android_with_fallback
- [ ] netbsd
- [x] rdrand
- [ ] rndr
- [ ] solaris
- [ ] solid
- [x] use_file (checked via linux_android_with_fallback)
- [ ] vxworks
- [x] wasi
- [x] wasm_js (can not be checked)
- [ ] windows7
- [ ] windows

**Comment by newpavlov** [comment]
Closing this issue since the most important backends are covered and we do not have a clear path forward for the remaining ones.
